steps:
  - name: "gcr.io/cloud-builders/docker:latest"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/financial-report-bff:$BRANCH_NAME",
        ".",
      ]
    logsBucket: "gs://my-logs-bucket"
  - name: "gcr.io/cloud-builders/gcloud:latest"
    args:
      [
        "app",
        "deploy",
        "financial-report-bff",
        "--image",
        "gcr.io/$PROJECT_ID/financial-report-bff:latest",
      ]
images:
  - "gcr.io/$PROJECT_ID/financial-report-bff:latest"
