steps:
  - id: Build project
    name: maven:3-openjdk-17
    entrypoint: mvn
    args: ["clean", "install", "-DskipTests=true"]

  - id: Build docker image
    name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/financial-report-bff:$latest", "."]

  - id: Push docker image
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/financial-report-bff:$latest"]

  - id: "deploy"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "financial-report-bff",
        "--image",
        "gcr.io/$PROJECT_ID/financial-report-bff:latest",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
      ]
images:
  - "gcr.io/$PROJECT_ID/financial-report-bff:latest"
options:
  logging: CLOUD_LOGGING_ONLY
